package db

const userSeed = `
INSERT INTO user (id, username, displayName, apiKey)
VALUES
(31568083,	"soulxburn", "SouLxBurN", "abcd1234"),
(236797464,	"kinda_cringe_dev", "kinda_cringe_dev", "1234abcd")
`
const streamConfigSeed = `
INSERT INTO stream_config (
    userId,
    botDisabled,
    firstEnabled,
    firstEpoch,
    qotdEnabled,
    qotdEpoch,
    dateUpdated)
VALUES
(31568083,false,true,DATETIME(),true,DATETIME(),DATETIME()),
(236797464,false,true,DATETIME(),true,DATETIME(),DATETIME())
`

const migrateConfigs = `
INSERT INTO stream_config(userId, botDisabled, firstEnabled, firstEpoch, qotdEnabled, qotdEpoch, dateUpdated)
SELECT u.id, false, true, '0001-01-01 00:00:00', true, '0001-01-01 00:00:00', datetime() FROM user u WHERE apiKey IS NOT NULL;
`

const questionSeed = `
INSERT INTO question(text)
VALUES
("What's the best piece of advice you've ever received?"),
("If you could have any superpower, what would it be and why?"),
("What's your favorite way to relax after a long day?"),
("If you could travel anywhere in the world right now, where would you go?"),
("What's the last book you read or movie you watched that you couldn't put down?"),
("What's the most memorable meal you've ever had?"),
("If you could have dinner with any historical figure, who would it be and why?"),
("What's the most adventurous thing you've ever done?"),
("If you could instantly learn any skill, what would it be?"),
("What's your favorite way to spend a weekend?"),
("What's the most interesting thing you've learned recently?"),
("If you could only eat one type of cuisine for the rest of your life, what would it be?"),
("What's your favorite hobby or pastime?"),
("If you could meet any fictional character, who would it be and why?"),
("What's the best concert or live performance you've ever attended?"),
("What's the most challenging thing you've ever accomplished?"),
("If you could have a conversation with your future self, what would you ask?"),
("What's one thing you've always wanted to try but haven't had the opportunity yet?"),
("If you could choose a new name for yourself, what would it be?"),
("What's your favorite quote or mantra that inspires you?"),
("If you could magically become fluent in any language, which one would you choose?"),
("What's the best piece of advice you would give to your younger self?"),
("What's the most beautiful place you've ever visited?"),
("If you were stranded on a desert island, what three items would you want to have with you?"),
("What's the most interesting job you've ever had?"),
("If you could be an expert in any field, what would it be?"),
("What's the most courageous thing you've ever done?"),
("If you could have dinner with any celebrity, who would you choose?"),
("What's your favorite way to stay active and fit?"),
("If you could invent a new technology, what problem would it solve?"),
("What's your favorite board game or card game?"),
("If you could time travel, which era or event would you visit?"),
("What's one skill or hobby you've always wanted to learn but haven't yet?"),
("If you could have any animal as a pet, what would you choose?"),
("What's your favorite season and why?"),
("If you could trade lives with someone for a day, who would it be?"),
("What's the most memorable gift you've ever received?"),
("If you could eliminate one chore or task from your life forever, what would it be?"),
("What's your favorite way to show kindness to others?"),
("If you could witness any historical event, what would it be?"),
("What's your go-to karaoke song?"),
("If you could have a dinner party with three famous people, living or deceased, who would you invite?"),
("What's your favorite way to celebrate your birthday?"),
("If you could master any musical instrument, which one would you choose?"),
("What's your favorite way to de-stress or unwind?"),
("If you could be a character in a book or movie, who would you be and why?"),
("What's the most valuable lesson you've learned from a failure or mistake?"),
("If you could live in any fictional world, where would you choose to live?"),
("What's the best piece of advice you would give to someone starting a new job or career?"),
("If you could have a conversation with any historical figure, who would it be and what would you ask them?"),
("What's your favorite outdoor activity or sport?"),
("If you could have an unlimited supply of one thing, what would it be?"),
("What's your favorite way to practice self-care?"),
("If you could be an expert in any form of art, what would you choose?"),
("What's the most interesting fact you've learned recently?"),
("If you could have a personal chef, what type of food would you want them to prepare?"),
("What's the most memorable concert or live performance you've ever attended?"),
("If you could spend a day with any fictional character, who would it be and what would you do together?"),
("What's your favorite way to give back to your community?"),
("If you could have a conversation with any animal, which one would you choose and what would you ask?"),
("What's your favorite type of dessert?"),
("If you could have any career, regardless of qualifications or training, what would you choose?"),
("What's the best piece of advice you've ever received about relationships?"),
("If you could have a home anywhere in the world, where would it be?"),
("What's the most interesting documentary you've ever watched?"),
("If you could bring back any fashion trend, what would it be?"),
("What's your favorite way to start your day?"),
("If you could meet any famous athlete, who would you choose?"),
("What's the most thrilling adventure or activity you've ever experienced?"),
("If you could have any vehicle, whether it's practical or not, what would you choose?"),
("What's your favorite way to express your creativity?"),
("If you could solve one global problem, what would it be and why?"),
("What's your favorite way to spend quality time with friends or family?"),
("If you could have any fictional character as a best friend, who would it be and why?"),
("What's the most interesting historical fact you know?"),
("If you could have a conversation with any person, dead or alive, who would it be and why?"),
("What's your favorite way to learn something new?"),
("If you could have a lifetime supply of any snack, what would you choose?"),
("What's the most unusual food you've ever tried?"),
("If you could be a contestant on any game show, which one would you pick?"),
("What's your favorite way to stay motivated and productive?"),
("If you could visit any planet in the solar system, which one would you choose and why?"),
("What's the most inspiring book you've ever read?"),
("If you could witness any natural phenomenon, what would it be?"),
("What's your favorite type of music or favorite band/artist?"),
("If you could bring any fictional character to life, who would it be and why?"),
("What's the best piece of advice you would give to someone about pursuing their dreams?"),
("If you could have dinner with any family member, living or deceased, who would you choose and why?"),
("What's your favorite way to explore new places or cities?"),
("If you could have any animal talent or ability, what would it be?"),
("What's the most interesting historical landmark you've ever visited?"),
("If you could learn a new language instantly, which one would you choose and why?"),
("What's your favorite way to overcome a challenge or obstacle?"),
("If you could have any job for a day, just to try it out, what would it be?"),
("What's the most memorable concert or live performance you've ever been a part of (as a performer or audience)?"),
("If you could be an expert in any form of dance, which one would you choose?"),
("What's your favorite way to connect with nature?"),
("If you could have any famous artist create a portrait of you, who would you choose?"),
("What's the best piece of advice you would give to someone about maintaining a healthy lifestyle?"),
("If you could be a character in a video game, who would you be and why?"),
("What's your favorite way to give yourself a mental or emotional boost?"),
("If you could have any fictional technology or gadget from a movie, what would it be?"),
("What's the most interesting animal fact you know?"),
("If you could have a conversation with any musician, living or deceased, who would you choose and why?"),
("What's your favorite way to stay organized and manage your time effectively?"),
("If you could visit any historical era as an observer, which one would you choose and why?"),
("What's the most memorable sporting event you've ever attended?"),
("If you could have any mythical creature as a pet, what would you choose?"),
("What's your favorite way to express gratitude?"),
("If you could have a talent in any form of performing arts, which one would you choose?"),
("What's the most interesting scientific discovery or concept you've come across?"),
("If you could have any job in the world, regardless of qualifications or salary, what would you choose?"),
("What's your favorite way to enjoy a rainy day?"),
("If you could have any historical artifact in your possession, what would it be?"),
("What's the best piece of advice you would give to someone about pursuing their passions?"),
("If you could have any animal as a sidekick, which one would you choose?"),
("What's your favorite way to unwind and relax on a Friday night?"),
("If you could learn instantly and master any instrument, which one would you choose?"),
("What's the most interesting historical event you've ever studied?"),
("If you could have a dinner party with any three people, living or deceased, who would you invite?"),
("If you could live in any fictional universe, which one would you choose?"),
("What's the most unique or unusual talent you possess?"),
("What's your favorite way to stay motivated and inspired?"),
("If you could have any job in the world, without worrying about money or qualifications, what would you choose?"),
("If you could have a conversation with any historical figure, who would you choose and why?"),
("What's your favorite way to spend a lazy Sunday morning?"),
("If you could instantly learn any language, which one would you choose and why?"),
("If you could have a superpower for a day, what would you choose and how would you use it?"),
("What's your favorite way to start your day on a positive note?"),
("If you could have any famous artist create a portrait of you, who would you choose and why?"),
("If you could bring back any fashion trend from the past, which one would it be?"),
("If you could travel back in time and give your younger self advice, what would it be?"),
("If you could have any animal's ability or trait, which one would you choose?"),
("What's your favorite way to practice self-care and prioritize your well-being?"),
("If you could have a conversation with your future self, what advice or questions would you share?"),
("What's your favorite way to explore and discover new things in your city or town?"),
("If you could have dinner with any fictional character, who would you choose and why?"),
("If you could have any career for a day, just to try it out, what would it be?"),
("What's your favorite way to celebrate special occasions?"),
("If you could bring one extinct animal back to life, which one would you choose?"),
("What's the most interesting piece of trivia about yourself?"),
("If you could learn any form of dance instantly, which one would you choose?"),
("What's your favorite way to spark your creativity or find inspiration?"),
("What's the most interesting historical landmark or site you've ever visited?"),
("If you could have any technological innovation become a reality, what would you choose?"),
("What's your favorite way to spend quality time with your loved ones?"),
("If you could have any famous athlete's skills for a day, who would you choose?"),
("What's your favorite way to connect with nature and the outdoors?"),
("If you could be an expert in any form of art, which one would you choose?"),
("What's the most interesting piece of information or news you've come across recently?"),
("What's the most interesting animal fact or behavior you know?"),
("If you could have a personal chef for a week, what type of food would you want them to prepare?"),
("What's your favorite way to stay organized and manage your tasks effectively?"),
("If you could have any historical artifact in your possession, what would it be and why?"),
("What's your favorite way to enjoy a sunny day?"),
("If you could be a contestant on any reality TV show, which one would you pick?"),
("What's the most memorable piece of advice you've ever received about success and achieving goals?"),
("If you could have any fictional character's wardrobe, whose would you choose?"),
("What's your favorite way to give yourself a mental break and relax your mind?"),
("If you could have any celebrity as your mentor, who would you choose and why?"),
("What's the most interesting fact or story about your family history?"),
("If you could have a conversation with any artist, living or deceased, who would you choose and why?"),
("What's your favorite way to challenge yourself and step out of your comfort zone?"),
("If you could have any magical ability or power, what would it be?"),
("What's the most interesting scientific discovery or concept you've come across recently?"),
("If you could visit any country in the world, where would you go and what would you do?"),
("What's your favorite way to give yourself a creative outlet?"),
("If you could have a conversation with any character from a TV show, who would you choose and why?"),
("What's the most memorable event or celebration you've ever attended?"),
("If you could have any famous artist's artwork displayed in your home, whose would you choose?"),
("What's your favorite way to overcome a challenge or obstacle in your life?"),
("If you could be a master of any form of martial arts, which one would you choose?"),
("What's the most interesting piece of technology you've come across recently?"),
("If you could have any profession for a day, just to experience it, what would it be?"),
("What's your favorite way to relax and recharge during a vacation?"),
("What's the most interesting piece of trivia you know about a famous landmark or monument?"),
("If you could have a conversation with any mythical creature, which one would you choose and what would you ask?"),
("What's your favorite way to learn new things or acquire new skills?"),
("If you could have any famous actor or actress star in a movie about your life, who would you choose?"),
("What's the most adventurous or daring thing you've ever done while traveling?"),
("If you could have a conversation with any historical leader or ruler, who would you choose and why?"),
("What's your favorite way to express your gratitude towards others?"),
("If you could have any celebrity's fashion sense, whose wardrobe would you choose?"),
("What's the most interesting natural phenomenon you've ever witnessed?"),
("If you could have a conversation with any musician from a different era, who would you choose and why?"),
("What's your favorite way to overcome creative blocks or writer's block?"),
("If you could attend any major sporting event, which one would you choose and why?"),
("What's the most memorable piece of advice you've received from a family member or loved one?"),
("If you could have any famous writer or author write your biography, who would you choose and why?"),
("What's your favorite way to learn about different cultures and traditions?"),
("If you could be a character in a fairy tale, who would you be and why?"),
("What's the most interesting historical fact or event from your own country?"),
("If you could have a conversation with any comedian, living or deceased, who would you choose and why?"),
("What's your favorite way to stay mentally sharp and challenge your mind?"),
("If you could have any fictional vehicle or transportation device, what would it be?"),
("What's the most memorable adventure or expedition you've ever been on?"),
("If you could have any job related to the arts, which one would you choose?"),
("What's your favorite way to express your creativity in everyday life?"),
("If you could have a conversation with any philosopher, who would you choose and why?"),
("What's the most interesting piece of trivia you know about a famous celebrity?"),
("If you could have any superpower related to knowledge or learning, what would it be?"),
("What's your favorite way to celebrate personal achievements or milestones?"),
("If you could be a character in a famous painting, which one would you choose?"),
("What's the most memorable concert or live performance you've ever watched online?"),
("If you could have any historical document or manuscript in your possession, what would it be?"),
("What's your favorite way to enjoy nature and the great outdoors?"),
("If you could have any famous chef cook a meal for you, who would you choose and why?"),
("What's the most interesting fact you've learned about space or the universe?"),
("If you could have a conversation with any leader or influential figure, who would you choose and why?"),
("What's your favorite way to boost your confidence and self-esteem?"),
("If you could have any famous athlete's skills in a specific sport, which sport and athlete would you choose?"),
("What's the most memorable gift you've ever given to someone?"),
("If you could solve one social issue or challenge, what would it be and why?"),
("What's your favorite way to connect with others and build meaningful relationships?"),
("If you could have any historical artifact from ancient civilizations, what would you choose and why?"),
("What's your favorite way to enjoy a sunset or sunrise?"),
("If you could be a contestant on any cooking show, which one would you pick?"),
("What's the most valuable piece of advice you would give to your future self?"),
("If you could bring any fictional creature to life, which one would you choose and why?"),
("What's your favorite way to learn about history and explore the past?"),
("If you could have a conversation with any business tycoon or entrepreneur, who would you choose and why?"),
("What's the most interesting cultural tradition or festival you've ever experienced?"),
("If you could have any famous actor or actress portray you in a movie, who would you choose and why?"),
("What's your favorite way to escape reality and immerse yourself in a different world (books, movies, video games, etc.)?"),
("If you could have any technology invented to simplify your daily life, what would it be?"),
("What's the most interesting piece of trivia you know about your favorite hobby or interest?"),
("If you could have a conversation with any influential scientist, who would you choose and why?"),
("What's your favorite way to volunteer and make a positive impact in your community?"),
("If you could be a character in a historical novel, which time period would you choose?"),
("What's the most memorable event or party you've ever organized?"),
("If you could have any famous artist create a mural on your home's exterior, who would you choose?"),
("What's your favorite way to stay positive and maintain a optimistic mindset?"),
("If you could be an expert in any form of visual arts, which one would you choose?"),
("What's the most interesting scientific experiment or study you've ever heard of?"),
("If you could have any famous singer perform at your wedding, who would you choose?"),
("What's your favorite way to practice mindfulness and be present in the moment?"),
("If you could have any fictional vehicle from a sci-fi movie, which one would you choose?"),
("What's the most interesting animal behavior or adaptation you've learned about?"),
("If you could have a conversation with any historical inventor or scientist, who would you choose and why?"),
("What's your favorite way to surprise or delight someone special in your life?"),
("If you could have any profession from a different era, which one would you choose?"),
("What's the most memorable adventure or excursion you've ever been on with friends or family?"),
("If you could have any superhero's costume, which one would you choose?"),
("What's your favorite way to stimulate your mind and engage in intellectual discussions?"),
("If you could have a conversation with any musician from a different genre, who would you choose and why?"),
("What's the most interesting piece of trivia you know about a historical figure?"),
("If you could have any famous actor or actress as your mentor, who would you choose and why?"),
("What's your favorite way to give back to the environment and practice sustainability?"),
("If you could attend any major award show, which one would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous landmark?"),
("If you could have any magical item from a fantasy book or movie, what would it be?"),
("What's your favorite way to stimulate your creativity and generate new ideas?"),
("If you could have a conversation with any literary character, who would you choose and why?"),
("What's the most memorable event or celebration you've ever hosted?"),
("If you could have any famous artist create a sculpture of you, who would you choose and why?"),
("What's your favorite way to relax and find inner peace?"),
("If you could have any character from a TV show as your best friend, who would you choose and why?"),
("What's the most interesting piece of trivia you know about a famous historical battle?"),
("If you could have a conversation with any philosopher or thinker, living or deceased, who would you choose and why?"),
("What's your favorite way to challenge yourself physically and stay fit?"),
("If you could have any fictional power from a comic book, what would it be?"),
("What's your favorite way to support and uplift others in your community?"),
("If you could attend any major music festival, which one would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous work of art?"),
("If you could have a conversation with any historical figure from your country, who would you choose and why?"),
("What's your favorite way to stay motivated and achieve your goals?"),
("If you could have any famous actor or actress as your co-star in a movie, who would you choose and why?"),
("What's the most memorable event or celebration you've ever attended as a guest?"),
("If you could have any famous architect design your dream home, who would you choose and why?"),
("What's your favorite way to explore and learn about different cuisines and culinary traditions?"),
("If you could have a conversation with any sports legend, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a historical invention?"),
("If you could have any musical instrument masterfully played for you, which one would you choose?"),
("What's your favorite way to practice gratitude and appreciate the little things in life?"),
("If you could attend any major film premiere, which movie would you choose and why?"),
("What's the most interesting historical fact or event from a country you've always wanted to visit?"),
("If you could have a conversation with any influential figure from the fashion industry, who would you choose and why?"),
("What's your favorite way to support local businesses and artisans?"),
("If you could have any famous actor or actress narrate your life story, who would you choose and why?"),
("What's the most memorable event or celebration you've ever organized as a host?"),
("If you could have any famous fashion designer create a custom outfit for you, who would you choose and why?"),
("What's your favorite way to embrace and appreciate different cultures and diversity?"),
("If you could have a conversation with any scientist or researcher, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical figure?"),
("If you could have any famous athlete as your personal coach, who would you choose and why?"),
("What's your favorite way to immerse yourself in a different time period or era?"),
("If you could have any famous actor or actress perform a monologue written specifically for you, who would you choose and why?"),
("What's the most memorable event or celebration you've attended as a participant or performer?"),
("If you could have any famous artist create a customized tattoo for you, who would you choose and why?"),
("What's your favorite way to give back and support charitable causes?"),
("If you could attend any major fashion show, which one would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical document?"),
("If you could have a conversation with any influential figure from the technology industry, who would you choose and why?"),
("What's your favorite way to celebrate and appreciate the achievements of others?"),
("If you could have any famous actor or actress as your scene partner in a play, who would you choose and why?"),
("What's the most memorable event or celebration you've ever participated in as an organizer or planner?"),
("If you could have any famous architect design a landmark for your city, who would you choose and why?"),
("What's your favorite way to explore and experience different culinary traditions from around the world?"),
("If you could have a conversation with any legendary sports coach, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical discovery?"),
("If you could have any musical instrument played by a world-renowned musician, which one would you choose?"),
("What's your favorite way to express appreciation and gratitude towards others?"),
("If you could attend any major theater production, which one would you choose and why?"),
("What's the most interesting historical fact or event from a country you've always been fascinated by?"),
("If you could have a conversation with any influential figure from the beauty industry, who would you choose and why?"),
("What's your favorite way to support local artists and creatives in your community?"),
("If you could have any famous actor or actress perform a dramatic reading of your favorite book, who would you choose and why?"),
("What's the most memorable event or celebration you've ever attended as a guest of honor?"),
("If you could have any famous fashion designer create a one-of-a-kind outfit for you, who would you choose and why?"),
("What's your favorite way to embrace cultural diversity and learn about different customs and traditions?"),
("If you could have a conversation with any renowned scientist, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical period?"),
("If you could have any famous athlete as your training partner, who would you choose and why?"),
("What's your favorite way to immerse yourself in a different cultural experience or festival?"),
("If you could have any famous actor or actress star in a play written by you, who would you choose and why?"),
("What's the most memorable event or celebration you've ever organized as a host with a specific theme?"),
("If you could have any famous architect design your dream workplace or office, who would you choose and why?"),
("What's your favorite way to explore different flavors and cuisines through food tastings or culinary tours?"),
("If you could have a conversation with any influential figure from the automotive industry, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical artifact?"),
("If you could have any musical instrument played by a world-class orchestra, which one would you choose?"),
("What's your favorite way to express gratitude and acknowledge the contributions of others?"),
("If you could attend any major art exhibition, which one would you choose and why?"),
("What's the most interesting historical fact or event from a country you've always wanted to explore further?"),
("If you could have a conversation with any renowned inventor or engineer, who would you choose and why?"),
("What's your favorite way to support local sports teams and athletes in your community?"),
("If you could have any famous actor or actress perform a monologue written by you, who would you choose and why?"),
("What's the most memorable event or celebration you've ever attended related to a specific hobby or interest?"),
("If you could have any famous architect design a park or public space in your city, who would you choose and why?"),
("What's your favorite way to try new recipes and experiment with different cooking techniques?"),
("If you could have a conversation with any influential figure from the aviation industry, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical figure's personal life?"),
("If you could have any musical instrument played by a world-renowned band or ensemble, which one would you choose?"),
("What's your favorite way to express appreciation and gratitude towards nature and the environment?"),
("If you could attend any major dance performance or show, which one wouldyou choose and why?"),
("What's the most interesting historical fact or event from a country you've always been curious about?"),
("If you could have a conversation with any influential figure from the film industry, who would you choose and why?"),
("What's your favorite way to support local theater productions and performing arts organizations?"),
("If you could have any famous actor or actress star in a movie that you write and direct, who would you choose and why?"),
("What's the most memorable event or celebration you've ever attended as a guest of honor, related to a specific interest or passion of yours?"),
("If you could have any famous architect design a museum or gallery dedicated to your favorite subject, who would you choose and why?"),
("What's your favorite way to explore different culinary traditions and cuisines through food festivals or international food fairs?"),
("If you could have a conversation with any influential figure from the gaming industry, who would you choose and why?"),
("What's the most interesting fact or piece of trivia you know about a famous historical figure's achievements or contributions?"),
("If you could have any musical instrument played by a renowned musician in a private concert, which one would you choose?")
`

const exclusionListSeed = `
INSERT INTO exclusion(username)
VALUES
("007_bad_girl"),
("00tylerpyt"),
("01aaliyah"),
("01ella"),
("01linn"),
("01olivia"),
("0ax2"),
("0liavanna"),
("0liveanne"),
("0livianna"),
("0lyvia_"),
("0maisie"),
("0nayli"),
("0_nekopara_0"),
("0niva"),
("0_supa"),
("0turt"),
("0x45"),
("0x626f74"),
("0xtackling"),
("1174"),
("17hao"),
("1aliveafricajouhzu"),
("1a_twitch_emoticons_show_"),
("1fps"),
("1illllllll"),
("1nittogether"),
("1psylo"),
("2020"),
("21bender"),
("240p"),
("24_7_chatting_on_discord"),
("360vinz"),
("3jask"),
("420f1tc00l"),
("47vres"),
("4fxz"),
("7bvllet"),
("7hvdes"),
("7tvapp"),
("8466321"),
("89002858303"),
("9kmmrbot"),
("a1bear"),
("a2100"),
("aadelead4271"),
("aantho7991"),
("abandoan4579"),
("abardea211"),
("abbottcostello"),
("abeornald9345"),
("abert3020"),
("abethbryt4751"),
("abjuui"),
("aboutw"),
("absterchen"),
("abstractedduck"),
("academyimpossible"),
("achofapelb"),
("actionshin"),
("actually__hannah"),
("adamstraubel"),
("adeptw"),
("adhdpex"),
("adoccome2214"),
("adonra9967"),
("adrianabarbero"),
("advocateplatform"),
("adwin666"),
("aeadlay4181"),
("aedsan6379"),
("aemyae_"),
("aeroverra"),
("afk_as_usual"),
("afortinter7358"),
("afridwise2282"),
("ag458624"),
("agent347"),
("agilet"),
("agormaferth848"),
("aguthjeff8179"),
("ahhahahahhahhahahhaahahah"),
("aidanx2"),
("aimiuwuu"),
("ajefflas6920"),
("ajoferth7332"),
("ajomuel4493"),
("aka_dev_acc"),
("akafred5548"),
("akseleron03"),
("aladra8920"),
("alanccw"),
("aleedo5274"),
("alettni6661"),
("alexdkvip"),
("alexii221"),
("alexisthenexis"),
("alexsaurora27"),
("alexthegamer0112"),
("aliceydra"),
("alienconglomeration"),
("aliengathering"),
("allenbuddy"),
("allenek12"),
("allroadsleadtothealien"),
("allroadsleadtothefarm"),
("alltow"),
("alo_da12"),
("alonmizrhai"),
("alucain"),
("alwaysbot"),
("alxiosbot"),
("amandampn"),
("ambellach"),
("amelaura"),
("ameliadp"),
("ampersandricky"),
("ananniel8571"),
("anarchyoss"),
("anastaysiia"),
("anethan4466"),
("angeeliwnl"),
("anna_banana_10"),
("anonymousboy15"),
("anotherttvviewer"),
("anothertvvviewer"),
("anthony0lzpyn"),
("anthony7l8m1n"),
("anthonyorr97i"),
("anthropologydept"),
("antonia_stream"),
("antoni_jastrzab"),
("anytow"),
("a_ok"),
("aordri7807"),
("apaulthony8149"),
("apiiscool"),
("applepiechart"),
("apugathering"),
("apumusic"),
("apuuuuuuuuuuuuuuuuu"),
("arahthor8746"),
("arcoender"),
("arctlco"),
("argonya_play"),
("aric775"),
("arierie1956"),
("ariscrow3977"),
("arnofps"),
("artaommahe"),
("aru444"),
("aruzhul1vh"),
("as48957210"),
("asam2861"),
("asangrim3563"),
("a_sasa"),
("asdpex"),
("aseanken8566"),
("aservicestop"),
("ashetray21"),
("ashhcrimson"),
("asmring"),
("asukamikasa"),
("aten"),
("athaetim9590"),
("atine5343"),
("atolisen5634"),
("atomcon3545"),
("audycia"),
("auroralblue"),
("autocrats"),
("autoiam"),
("avasemaphore"),
("avocadoofdoom"),
("awilpaul2701"),
("axletrees"),
("azurezu"),
("babasababapog"),
("baby_mochichan"),
("ball857"),
("bambooozeld"),
("bananennanen"),
("bandsan6780"),
("baran6470"),
("basiclybeau"),
("basstiiz"),
("bathas3966"),
("bbangddeock"),
("bbarliam4683"),
("bcomewaru4014"),
("bdansa5768"),
("bdodcon69"),
("beardedstrumerwaitingroom"),
("bearfish1"),
("bear_wit_me"),
("benjaminenetaniahu"),
("benoitsr"),
("benson77665"),
("bescmen3379"),
("betakew"),
("bethalda"),
("beverca1209"),
("bgrimfrid8851"),
("bhamfrith3245"),
("bigbobs"),
("bigbz0"),
("bigmonitor69"),
("bilikirs"),
("bimetallismb"),
("bingcortana"),
("birdant1"),
("bitstorm_"),
("bjomark2400"),
("blade2588"),
("blafwise5658"),
("blauwyn1830"),
("blazenplays"),
("blen2059"),
("blenhe6936"),
("bleof2237"),
("blerp"),
("blgdamjudge"),
("blinso120"),
("blkheroeseverywhere"),
("bloodlustr"),
("bloodyliferp"),
("bluedreamgocrazy"),
("blup"),
("bmannsa9713"),
("bmondley7590"),
("bmondris9853"),
("bnald3267"),
("bnanwine1411"),
("bnecrow7950"),
("boayeckfolkway"),
("bobsledded"),
("bongbar"),
("borahcar4649"),
("bossundee"),
("botdescartos"),
("bot_illskillz"),
("botisimo"),
("boxislove"),
("bpeke2274"),
("brahdryt2517"),
("brian13nkg7"),
("briancbe4ak"),
("brianqpa0sj"),
("brianyn8h7r"),
("brich2669"),
("brickev378"),
("bristlerich"),
("brokemystreamdeck"),
("brokenchairmedia"),
("brokenracedirector"),
("broman866"),
("brunamarque"),
("brutallabs"),
("bryste2472"),
("bsephacar1420"),
("bstanthas1618"),
("bswithken8619"),
("btheodber8002"),
("bthywil1645"),
("btolruth8776"),
("btovar3"),
("bu1zer"),
("buccoro"),
("bucksumlimb"),
("bunnyrabbithole1"),
("business_daddy"),
("businesss"),
("buttsbot"),
("bwarddino3954"),
("bydyhelokw"),
("bzadoc5383"),
("c_1_3_7_"),
("camistheman596"),
("captainskrew"),
("captinconman"),
("carbob14xyz"),
("carbon14xyz"),
("carbot14xyz"),
("cardboard_live"),
("carsu5975"),
("cartierlogic"),
("casinothanks"),
("cbri8583"),
("cdicgar6358"),
("ceadda7085"),
("centenarys"),
("cferard3983"),
("cferumbard2808"),
("cfredtheod3377"),
("cgajen8369"),
("cgardtol4209"),
("chaimrevivo"),
("challacc"),
("charleslxjezw"),
("charlesor3g0j"),
("chat_analytics"),
("chatchatchatchatchatchat_"),
("chat_for_gamers"),
("chatlgpt"),
("chatstats_"),
("chattranslator"),
("cheferd1769"),
("chesing5330"),
("chianchianxiannuovo"),
("chillfireplaceasmr"),
("choppering"),
("christopher4peb1f"),
("christopherc241a2"),
("cingha1320"),
("cjeffpa1110"),
("claever4990"),
("claire_sir_chistory"),
("cleaning_the_house"),
("cleeric749"),
("cleofuhal330"),
("clipebox"),
("cmaxald9776"),
("cmaxlaf2866"),
("cmenven2467"),
("cmeriferum2205"),
("cnathret9629"),
("cneacarrah3003"),
("cnipaul5573"),
("coauthoring"),
("cogwhistle"),
("columbusq"),
("comesma6127"),
("comettunes"),
("commanderadmin"),
("commanderroot"),
("commula"),
("community_18k_members"),
("community_for_streamers"),
("communityshowcase"),
("competitivestreamwatcher"),
("conesericite"),
("copypastekappabot"),
("cosmicbeefmonster"),
("coubzilla"),
("crazycynical"),
("crazyic"),
("creatisbot"),
("creatorsunite"),
("credhal8503"),
("crictho7527"),
("crobma6879"),
("cronnath9232"),
("cronwaru9390"),
("crunchipchip"),
("csogard4247"),
("cstanken6293"),
("cswithria5848"),
("cthrythtine3566"),
("cubeit"),
("cubtree"),
("cuead512"),
("cuesta_carlos99"),
("cutehealgirl"),
("cwerdphie8369"),
("cwig5592"),
("cwise3159"),
("cyndyka"),
("cyotaffer"),
("d3nnyyyz"),
("d4rk_5how"),
("d4rk_5ky"),
("dachshund_bertha"),
("dailydayna"),
("daniel9rabf7"),
("danieladyqux"),
("danielefrrmf"),
("danitronics"),
("dankingaround"),
("dankrit"),
("darkidraws"),
("darktony999"),
("darkumaru729"),
("david3cetqd"),
("davidbengurion1"),
("davidyzkycm"),
("davilegt"),
("davyla_"),
("de127"),
("deafcold"),
("debymore"),
("decafsmurf"),
("defb"),
("defeat____"),
("delotx"),
("delteerdata"),
("delteerdatap1"),
("delteerdatap10"),
("delteerdatap11"),
("delteerdatap12"),
("delteerdatap13"),
("delteerdatap14"),
("delteerdatap15"),
("delteerdatap16"),
("delteerdatap17"),
("delteerdatap2"),
("delteerdatap3"),
("delteerdatap4"),
("delteerdatap5"),
("delteerdatap7"),
("delteerdatap8"),
("delteerdatap9"),
("demitidopelokled6"),
("dennitzo2"),
("der_dachshund"),
("derjonie"),
("devjimmyboy"),
("dhawnny"),
("diavolik8"),
("diavolik898"),
("digitalinstinct"),
("dinu"),
("discord4small_streamers"),
("discord_for_streamers__"),
("discord_for_streamez"),
("discordstreamercommunity"),
("dj_vermeer"),
("doll_house_surprise"),
("dominecaa"),
("don_broccoli"),
("donyduckz"),
("dorito_powder"),
("doudroupi"),
("dr3ddbot"),
("drapsnatt"),
("drdrewwork"),
("drlucylove"),
("droopdoggg"),
("druiefiery"),
("druperchy"),
("dsco"),
("dubsnhooters"),
("duckgoosovitz"),
("duffy356"),
("dukan_rex"),
("dunke2"),
("dynaterra"),
("dyniak__"),
("eadgaras"),
("eatsaoe"),
("eat_watch_play"),
("e_botas"),
("echtkpvl"),
("eddie85311"),
("edellyna"),
("edisonpts_228"),
("edward4rijf4"),
("eggman_92"),
("eggwhite99"),
("ehleon_"),
("ehrabz"),
("ehudbarak"),
("einfachfussel"),
("einfachuwe42"),
("eisenfutzi"),
("ekewyzhukei"),
("eklipse_chat_01"),
("eklipse_chat_02"),
("eklipse_chat_03"),
("eklipse_chat_04"),
("eklipse_chat_05"),
("eklipse_chat_06"),
("eklipse_chat_07"),
("eklipse_chat_08"),
("eklipse_chat_09"),
("eklipse_chat_10"),
("elbretweets"),
("electricallongboard"),
("electricalskateboard"),
("electricalwambo"),
("elenaberry"),
("elysian"),
("emersix"),
("emma_the_dilemmaa"),
("emperrorlp_"),
("empressiona"),
("empressnaila"),
("ensthor"),
("entryphones"),
("ep8bot"),
("ergolta"),
("erika_fnbr"),
("eunyss"),
("eveneo"),
("executive06"),
("expressways"),
("extramoar"),
("eyalberkovitz"),
("ezobay"),
("faegwent"),
("fake_vexxed"),
("faps247"),
("farminggurl"),
("fearms1"),
("feelsgoodmanlongusernames"),
("feet"),
("felixyhyunji"),
("fenrir0131"),
("ferriswirl2"),
("ffxivstyx"),
("fgcounterbot"),
("find_chan_to_raid"),
("fipspilot"),
("fish_0703"),
("fixloven"),
("flatearthchannel"),
("fleetbattle"),
("flex3rs"),
("floboytwi"),
("floboytwi_auf__twitch"),
("floboytwi_auf_twitch"),
("floboytwi_auf_twitch_"),
("fookstee"),
("forbearanceday"),
("fortnitebabe_"),
("foursilk"),
("francesco2345178"),
("freakybabetv"),
("freast"),
("freddy_lachance"),
("freedomhusky"),
("frendly"),
("frw33d"),
("frw33ds_kitten"),
("ftopayr"),
("fuoletovui_banan"),
("fwost"),
("fxhxyz"),
("galgoya"),
("galletita_de_queso"),
("gamers_and_streamers"),
("gamers__lounge"),
("gaversolo"),
("geall"),
("gemgoon"),
("george1m8jjx"),
("george7c18ma"),
("georgebye66"),
("georgec6yuvj"),
("georgegreenwhz"),
("georgew2ms8p"),
("geres2it"),
("ghosttg"),
("gigi1018"),
("gik_gok"),
("gingerne"),
("giveme_ssr"),
("gkiioo"),
("glasnosts"),
("glitchedkudzu"),
("glitterya"),
("gloft"),
("gochuuvovj"),
("goldameir1"),
("gonecizhecrc"),
("gongangingabioncfan"),
("goodgirlsage"),
("goth_girl_morgane"),
("gowithhim"),
("graphmau"),
("grifordia"),
("groundsoundfloor"),
("growyourchannelfree"),
("guava_520"),
("h4x0rgin"),
("h8scanner"),
("hades_osiris"),
("hak3r_bot"),
("hannahqt2"),
("hans93194"),
("havethis2"),
("heirmanttinan"),
("henry1874"),
("henry70122"),
("hentyechan"),
("herrheil"),
("hilda5433"),
("himanshurrrr"),
("holaitzcarmennn"),
("horsecow12"),
("hotclipsbot"),
("hqmes"),
("hypexis333"),
("iam_fady_og"),
("iamfannco"),
("iandy88"),
("iautohost"),
("icantcontrolit"),
("icaro12oliveira"),
("icewizerds"),
("i_emka"),
("ifrez_tv"),
("ii7331"),
("iisabei"),
("iizzybeth"),
("ijebenaie"),
("imamuracross"),
("immallytwitch"),
("imsorryjusttesting"),
("inaqt"),
("industrialparasite"),
("informationssicherheit"),
("inntblade"),
("inventkin"),
("iqijikuriu7"),
("isaacdeplar"),
("ismagokuph"),
("isnicable"),
("itsfolf"),
("itsthefrits"),
("itsvodoo"),
("itzemmaaaaaaa"),
("itzikkorenfine"),
("iviotic"),
("jackoplane"),
("jakken2"),
("jamesapwzaf"),
("jamesb7b7"),
("jamesi5gs80"),
("jamesmslsmz"),
("jameswilliamslxq"),
("jamjamjm9"),
("janinebans"),
("jasonc8l4wl"),
("jasonndx1iq"),
("jasonnvs1x4"),
("jasont7oqk4"),
("jason_thompsontym"),
("jasonwbhhz5"),
("jay123300"),
("jcdarui"),
("jdo432"),
("jeanzin019"),
("jebibot"),
("jeffersonviniciuslima"),
("jeffl0ab8p"),
("jenxwolf"),
("jessevn__"),
("jhodymoon"),
("jiffyonyx"),
("jigglegiggle"),
("jimmysqueeker"),
("jinal"),
("jmemo162"),
("joefrangieh7"),
("joestar_alfred"),
("johancoetsee"),
("john101505"),
("johnk4c55v"),
("jointeffortt"),
("jonas_"),
("joseluis31_"),
("joseph1zj6gg"),
("josephq2bb5f"),
("jsymons7"),
("juancabardo"),
("jubewe_ml"),
("junrui1027"),
("junweitw"),
("justcallmejuri"),
("just_friendly_neighbor"),
("just_in_chat"),
("justmariusz"),
("jyxeqakh"),
("k0ukiee"),
("kagami13"),
("kamicazi_7"),
("karisg1"),
("katojun_fan"),
("kattah"),
("kattynah"),
("kawanpls"),
("kaxips06"),
("kayla18067"),
("kekwkaka4040"),
("kennetht7yrun"),
("kenshiro26"),
("k_e_r_b_a"),
("kerbalcake"),
("kero____"),
("kevin746347"),
("kevin9rxxy9"),
("keystone45x"),
("kharliito"),
("kians_"),
("kikettebot"),
("kikkipasso"),
("kimberlybrowncss"),
("kishintern"),
("kittenrescue"),
("kittykat513"),
("kivavii"),
("kn_crypto"),
("knobo_"),
("kodiakbrujah"),
("kofistreambot"),
("kotaromaster"),
("kotyareg"),
("krolchatina_"),
("kyroskoh"),
("kyutmochimin"),
("ladaellada"),
("lady_bath_horey"),
("la_kaylee"),
("lanarayyyy"),
("lanfusion"),
("larakraf"),
("lattemotte"),
("lauradesk"),
("ledrty"),
("leftviews"),
("leiyicat"),
("le_manchot_geek"),
("lemon_gir"),
("lemonjuices12"),
("leonhart0620"),
("leuchtendesschaf"),
("levantinlynx_"),
("leviathanapp"),
("levieshkol"),
("lf2netk331"),
("lfgfusion"),
("limetimepop"),
("lionofyara"),
("lipton_tyan"),
("liquidpve"),
("literallyunreal"),
("ljlcard"),
("l____l"),
("llorx_falso"),
("l_nephilim_l"),
("logiceftbot"),
("lollyneuter"),
("lolrankbot"),
("lonely_liza"),
("lorypub"),
("losjaraswines"),
("love3555aa"),
("lowtik"),
("lucentcrown12345678910"),
("lucentcrown1234567891011"),
("luciferka_124"),
("lukanard"),
("luki4fun_bot_1"),
("luki4fun_bot_master"),
("lulu20170818"),
("lurkiefox"),
("lurkingchat"),
("lurxx"),
("lyfhael"),
("lylituf"),
("m1a2r3q4u5e6s7"),
("m3d1umx"),
("m4st3rx01"),
("maddynsun"),
("maddyson_moy_bog"),
("magi_system"),
("makerplier"),
("makimfh"),
("manning_wilkins"),
("mararomano"),
("maria_anderson_"),
("mariah_anderson_usa"),
("marinak0s"),
("marioshl"),
("mariotiss"),
("mark8bl82w"),
("markz_________"),
("markzynk"),
("martinbro197"),
("mary_robinsonqlz"),
("masked371"),
("masoqueeisso"),
("masradok"),
("mateo_g_g_"),
("maxlivestream"),
("maxxpsg"),
("mcd0m_"),
("mcd0m_bot"),
("mdaryaaacreep"),
("mee6dev"),
("mefyxeqyh2u"),
("memote_wall"),
("menachembegin1"),
("metaforick"),
("metaviews"),
("meverywhere"),
("micaela_v25"),
("michael2xdx0s"),
("michael_clarkxmk"),
("michael_lopezkgs"),
("michaelp6bip6"),
("michaelqagi5o"),
("michaelqmz35a"),
("michaelxfe5rg"),
("microlera"),
("midsooooooooon"),
("mightyass"),
("miguel86r"),
("mikuia"),
("minion619"),
("mirrobot"),
("misalo0515"),
("mizu_discord1"),
("mizu_discord2"),
("mizu_discord222"),
("mizu_discord3"),
("mizu_discord4"),
("mizu_discord5"),
("mizu_discord6"),
("mizu_discord7"),
("mizu_discord8"),
("mizu_discord9"),
("mogulmail"),
("moistkek"),
("moku_"),
("moobot"),
("morgane2k7"),
("mortie_play"),
("moshesharet"),
("mousegerry_"),
("mr"),
("mrjiz1"),
("mrnull01"),
("mtgbot"),
("music_and_arts"),
("mutalit"),
("myhuxilggk"),
("mystery_0911"),
("mystic_bolly"),
("naruto82u"),
("narutoblcak"),
("nathi_inacio"),
("natzelly"),
("nenialatnar"),
("nerdydreams"),
("networknetworknetwork"),
("network_streamer_discord"),
("newolk69"),
("newstreamers_support_chat"),
("nexysssss"),
("nicdipples"),
("nightbot"),
("nightchillbc"),
("nightmarejoker2"),
("nikover"),
("ninatela"),
("nintendoswitchxl"),
("nissisaki"),
("no4mt"),
("noblewolf"),
("noiz_bot"),
("nomooa"),
("nosmad5"),
("notabotdef11"),
("notabotdef12"),
("notabotdef13"),
("notabotdef14"),
("notabotdef15"),
("notabotdef16"),
("notabotdef17"),
("notabotdef2"),
("notabotdef3"),
("notabotdef4"),
("notabotdef5"),
("notabotdef6"),
("notabotdef8"),
("notabotdef9"),
("notamrbeastcontest"),
("not_real_holy"),
("nowbowseeder"),
("nsa_66"),
("nuxbot_com"),
("nyaetlolita"),
("o0followme0o"),
("obytukgpf"),
("o___c___o"),
("official_tubebot"),
("offlinegiggles"),
("ogilvy2"),
("olly415"),
("omegajeppe"),
("omg_fashionman"),
("omicron"),
("omynyrg1"),
("onlinegiggles"),
("onvoi"),
("ooo_star_ooo"),
("opontifex"),
("oqycizhu"),
("orbatos"),
("orthoduk"),
("ortholexy"),
("outside_gardening"),
("outside_working"),
("outtietv"),
("overlayexpert"),
("overthere86"),
("own3d"),
("pacopepeconstructor"),
("painfullest"),
("pandeon_22"),
("paradise_for_streamers"),
("patranovisinka"),
("paulaarrigui"),
("paulenvede"),
("paul_parkerwdt"),
("paulxliy91"),
("pbarreto18"),
("pboj"),
("pectoralmuscle"),
("peculiarasmr"),
("peepolurk"),
("peer2peerbot"),
("peritustv"),
("phantom_309"),
("phyton_tyan"),
("pikachu4ni"),
("pilotmikex"),
("pingutio"),
("pipe78900"),
("pixelbypixel_bot"),
("pixelstrikes"),
("play24hrs"),
("playwithviewersbot"),
("pmpmpalan"),
("pocrevocrednu"),
("pogli"),
("pokemoncommunitygame"),
("porowang"),
("potatomalonettv"),
("prankcher"),
("pretend2care"),
("pretzelrocks"),
("private_psyjic"),
("projectneurocam"),
("psdlxl_"),
("public_enemy821"),
("puptime"),
("qnfgogtktls"),
("qoqsik"),
("quynguyen10"),
("quynguyen104"),
("quynguyen153"),
("quynguyen30"),
("quynguyenvu"),
("ra1denz"),
("radiorelaxfm"),
("rafalo15"),
("rafczyk"),
("raidvirus"),
("rainmaker"),
("randomtwitchstats"),
("rans4cker"),
("rarecandyglitch"),
("rare__potato"),
("re1yk"),
("realj4zz"),
("rebornvn9999"),
("r_e_d_e_k"),
("redtailfoxxyy"),
("rekmux"),
("relishdrove"),
("remasuri_bot"),
("remyxygo7m"),
("renata82837"),
("restreambot"),
("reuvenatar"),
("rezign0604"),
("richard4vklcm"),
("richard9oipjx"),
("rietty"),
("rimastino"),
("risa_omari"),
("rkn_fry"),
("rladmsdb88"),
("rmenchik"),
("robertmhslx4"),
("roberttzx2jc"),
("robohubby"),
("robotman000"),
("robot_tyanxd"),
("roger60229"),
("rogueg1rl"),
("rogueshady"),
("rohliksmaslem1205"),
("romainstant1"),
("ronald2boby4"),
("ronaldl2al8u"),
("ronenharazi"),
("ronyrozental"),
("round_track_car"),
("roxesy"),
("rubberslayer"),
("rubbing"),
("runjerry"),
("rushymio"),
("rutonybot"),
("rvxze"),
("ryad_01"),
("rydannn"),
("ryothscus"),
("s03079"),
("s0uthkill"),
("sabrinnaalice"),
("sabsel1337"),
("saddestkitty"),
("sagadeathzero"),
("samskio"),
("santaclausgift"),
("saralna"),
("sarotainment"),
("sayonala_"),
("sayuu_0"),
("scratchdee"),
("seelosc"),
("segadream"),
("selvatigator"),
("senadani"),
("senolass"),
("servres"),
("sery_bot"),
("shadowy_stix"),
("shanuala"),
("shatimka"),
("shimeonperes"),
("shine_discord1"),
("shine_discord10"),
("shine_discord11"),
("shine_discord12"),
("shine_discord13"),
("shine_discord14"),
("shine_discord15"),
("shine_discord16"),
("shine_discord17"),
("shine_discord18"),
("shine_discord19"),
("shine_discord2"),
("shine_discord20"),
("shine_discord21"),
("shine_discord22"),
("shine_discord3"),
("shine_discord4"),
("shine_discord5"),
("shine_discord6"),
("shine_discord7"),
("shine_discord8"),
("shine_discord9"),
("shiningwing"),
("shlomosharf"),
("show__gg__"),
("show_gg_"),
("shypuf"),
("sicrone"),
("sigurniv"),
("simatashka"),
("simonedeboudoir"),
("sinisterlab"),
("sirrelu"),
("sixflagsmagicmountain"),
("sixset"),
("skilyrab"),
("skinnyseahorse"),
("skiptok"),
("skumshop"),
("slocool"),
("smallsteramersdcserver"),
("smallstreamersdccommunity"),
("smallstreamersdcserver"),
("smallstreamers_discord"),
("smatify_"),
("smiterholic"),
("socialstreamergrowth"),
("soicluberville"),
("solalamo_"),
("songlistbot"),
("sonyplaystations"),
("sopalidiseend"),
("sophiafox21"),
("sophikal"),
("soundalerts"),
("soundofraindrops"),
("soushi08"),
("sparker_watcher"),
("spazzyp254official"),
("spcrowetest"),
("speedysingh"),
("spehovacek"),
("spiketrapclair"),
("spofoh"),
("sport_scores_bot"),
("spraytorto"),
("springerj1243"),
("squu1zy"),
("srekrapstob"),
("srizbi"),
("srizbot"),
("srokates"),
("ssakdook"),
("ssgdcserver"),
("stankubrick"),
("statslogger"),
("stayhealthybot"),
("stay_home_bot"),
("stay_pepega_bot"),
("steven24nowl"),
("steven301411"),
("steven5wcgi5"),
("steven8a9uhd"),
("stevencfr1np"),
("stevenhv93kl"),
("stevenlopezhjk"),
("stewlew89"),
("stixffxiv"),
("storecina"),
("stormzinr"),
("strangebing"),
("stream_achievements"),
("streamdeckerbot"),
("streamelements"),
("streamer_page_discord"),
("streamers_growth"),
("streamers_social_space"),
("streamfahrer"),
("streamheroes"),
("streamholics"),
("streamkit"),
("streamlabs"),
("streamstat_pl"),
("streamstickers"),
("stripfang"),
("stygian_network"),
("stygian_styx"),
("sullygnome1"),
("sunamano"),
("supa8"),
("surelyiwontgetbanned"),
("sweetuser11"),
("swiftyspiffy"),
("sylithen"),
("tackling"),
("tacklingbot"),
("tacotuesday7313"),
("tada_cha"),
("taiwanstriker"),
("tamagucci_bot"),
("tanonjaeng"),
("tarkovchangesbot"),
("tavert0"),
("tawmtawmz"),
("teazyou"),
("teebeutel_d3luxe"),
("tehfl0w"),
("teischente"),
("temp_account100"),
("temp_account132"),
("tempest666_"),
("tensu____________________"),
("teresedirty"),
("testt64"),
("tetyys"),
("thatguybrayd"),
("theatomcrafter"),
("thebraverlurkerschweijkg"),
("thechilledtee"),
("thecommandergroot"),
("thedevilisob"),
("thefegirl"),
("thefishcannon"),
("thelurxxer"),
("thequeenttv__________"),
("theqwadfather"),
("therussianmommy"),
("thesoggy_"),
("thespacemonkey"),
("thesubwaybread"),
("thewritinger"),
("thiccur"),
("thirtysevenqt"),
("thisisunreallol"),
("thomasbjxiqc"),
("thomasmillerlfg"),
("thomasxjo6rx"),
("threebibl"),
("th_tony"),
("tiagolongaraymaia"),
("tinarif"),
("tizcloud"),
("toastyprime"),
("tommy57655"),
("trampel81"),
("tranziner"),
("tresinno"),
("trevyn201"),
("trewdalbert"),
("trianglegathering"),
("tteyyd"),
("ttv_rotom"),
("tullioofani"),
("turbopascai"),
("twilightxor"),
("twiscord_bot"),
("twitchcancermonitor"),
("twitchencouragement"),
("twitchhyperss"),
("twitchpastes_com"),
("twitchplays_zeldagames"),
("twitchstatstracker"),
("twitchstreamerdiscord"),
("tyzesc"),
("ult1mat3sn1p3z"),
("ultimafreak"),
("unbanjurilol"),
("uncannyai"),
("uncle_spawn"),
("underworldnaiad"),
("undiecraft"),
("universe"),
("unsist"),
("un_viri"),
("usb_keyboard_unplugged"),
("usernamelookup"),
("ustatsbot"),
("ustatsbot_cps"),
("ustatsbot_ekb"),
("ustatsbot_krs"),
("ustatsbot_spb"),
("valentinaalcaraz"),
("v_and_k"),
("vaterholl"),
("vaticancitymagoo"),
("verylonely_liza"),
("vesna16184"),
("viceeeen"),
("vicenbot"),
("victoriavictorylul"),
("victortomaili"),
("video_game_talk"),
("viewer_of_irl"),
("violetplxyzig"),
("violets_tv"),
("violets_tw"),
("virgoproz"),
("visiongaming2"),
("vivbot"),
("v_tel"),
("vtuberplus"),
("wafflebudder"),
("walker956"),
("wannabemygamerfriend"),
("waptart"),
("warsofthetrekgatestar"),
("weiliweiliweili"),
("weiwei823128"),
("welovemarbles"),
("whalepig1"),
("whataboutgaminglive"),
("whateverbichhh"),
("wholismr"),
("why_not_xxx"),
("whypepe"),
("whypepeisoffline"),
("william0pq0qd"),
("williamnmdu1q"),
("williamvea2rw"),
("willkoga"),
("wing2577"),
("winsock"),
("wizebot"),
("wo0sha"),
("wofflestoffle"),
("world_of_chatters"),
("world_of_streamers"),
("wpfid5555"),
("wsafwan"),
("wzbot"),
("x3_xto"),
("xcelinamarie"),
("xcr1zzly"),
("xeodk"),
("xerxes087"),
("xhylane"),
("xiaodeeeee"),
("xing1214"),
("x_nsa_x"),
("xokocodo"),
("xup663"),
("xvxxii"),
("xxdemonkitty"),
("xyfm"),
("yaazkalyoncu"),
("yamickle"),
("yapp1_"),
("yeezyjesuspeezus"),
("yeguaik"),
("yesimtheguy"),
("yete"),
("yhizhaba7fq"),
("yitzhakrabin3"),
("yitzhakshamir"),
("yologirlio"),
("yosgart2525"),
("yosharpi"),
("ypabup"),
("yubother"),
("yukiii__y"),
("yumi457"),
("yungjug1019"),
("yungsev_"),
("z1v1w1"),
("zalimsinzalim"),
("zayd_gb"),
("zerovero_"),
("zigulisegra"),
("zkeey"),
("zladk0"),
("znicuuu"),
("zokers_biggest_fan"),
("zombieocean"),
("zortingennnn"),
("z_rona"),
("zuclo32")
`
